name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: Install dependencies
      run: npm ci

    - name: Set up Git
      run: |
        git config --global user.email "deploy@orycion.com"
        git config --global user.name "Deploy"

        mkdir -p ~/.ssh/
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
      env:
        DEPLOY_KEY: ${{ secrets.GITHUB_DEPLOY_KEY }}

    - name: Deploy
      run: npm run deploy
