name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: Install dependencies
      run: npm ci

    - name: Set up Git
      run: |
        git config --global user.email "hello@orycion.com"
        git config --global user.name "Deploy"

    - name: Deploy
      run: npm run deploy
